/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.BorderLayout;
import oracle.jrockit.jfr.events.ContentTypeImpl;

/**
 *
 * @author LAB REDES
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        jInternalFrameMain.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameMain = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu_File = new javax.swing.JMenu();
        jMenuItem_exit = new javax.swing.JMenuItem();
        jMenu_Clients = new javax.swing.JMenu();
        jMenuItemClient = new javax.swing.JMenuItem();
        jMenu_Workers = new javax.swing.JMenu();
        jMenuItemWorker = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrameMain.setVisible(true);
        jInternalFrameMain.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jInternalFrameMainAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jInternalFrameMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jInternalFrameMainMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrameMainLayout = new javax.swing.GroupLayout(jInternalFrameMain.getContentPane());
        jInternalFrameMain.getContentPane().setLayout(jInternalFrameMainLayout);
        jInternalFrameMainLayout.setHorizontalGroup(
            jInternalFrameMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 713, Short.MAX_VALUE)
        );
        jInternalFrameMainLayout.setVerticalGroup(
            jInternalFrameMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 713, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");

        jMenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuBarMouseClicked(evt);
            }
        });

        jMenu_File.setText("File");
        jMenu_File.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_FileActionPerformed(evt);
            }
        });

        jMenuItem_exit.setText("Exit");
        jMenuItem_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_exitActionPerformed(evt);
            }
        });
        jMenu_File.add(jMenuItem_exit);

        jMenuBar.add(jMenu_File);

        jMenu_Clients.setText("Clients");
        jMenu_Clients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_ClientsMouseClicked(evt);
            }
        });
        jMenu_Clients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_ClientsActionPerformed(evt);
            }
        });

        jMenuItemClient.setBackground(new java.awt.Color(255, 51, 51));
        jMenuItemClient.setText("Registro");
        jMenuItemClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClientActionPerformed(evt);
            }
        });
        jMenu_Clients.add(jMenuItemClient);

        jMenuBar.add(jMenu_Clients);

        jMenu_Workers.setText("Workers");
        jMenu_Workers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_WorkersMouseClicked(evt);
            }
        });
        jMenu_Workers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_WorkersActionPerformed(evt);
            }
        });

        jMenuItemWorker.setText("Register");
        jMenuItemWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemWorkerActionPerformed(evt);
            }
        });
        jMenu_Workers.add(jMenuItemWorker);

        jMenuBar.add(jMenu_Workers);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrameMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrameMain)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem_exitActionPerformed

    private void jMenuItemWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemWorkerActionPerformed
        WorkerGUI wk= new WorkerGUI();   
        wk.setSize(1000,680);
        wk.setLocation(0,0);
        
        jInternalFrameMain.repaint();        
        jInternalFrameMain.add(wk, BorderLayout.CENTER);
        jInternalFrameMain.setVisible(true); 
        
        
    }//GEN-LAST:event_jMenuItemWorkerActionPerformed

    private void jMenu_WorkersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_WorkersActionPerformed

               
    }//GEN-LAST:event_jMenu_WorkersActionPerformed

    private void jMenuItemClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClientActionPerformed

        ClientGUI cl= new ClientGUI();   
        cl.setSize(1000,680);
        cl.setLocation(0,0);
        
        
        jInternalFrameMain.repaint();
        jInternalFrameMain.add(cl, BorderLayout.CENTER);
        jInternalFrameMain.setVisible(true); 
        

    }//GEN-LAST:event_jMenuItemClientActionPerformed

    private void jInternalFrameMainAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jInternalFrameMainAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jInternalFrameMainAncestorAdded

    private void jMenu_FileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_FileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_FileActionPerformed

    private void jMenu_ClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_ClientsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_ClientsActionPerformed

    private void jInternalFrameMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInternalFrameMainMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jInternalFrameMainMouseClicked

    private void jMenuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBarMouseClicked

    private void jMenu_ClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_ClientsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_ClientsMouseClicked

    private void jMenu_WorkersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_WorkersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_WorkersMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrameMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemClient;
    private javax.swing.JMenuItem jMenuItemWorker;
    private javax.swing.JMenuItem jMenuItem_exit;
    private javax.swing.JMenu jMenu_Clients;
    private javax.swing.JMenu jMenu_File;
    private javax.swing.JMenu jMenu_Workers;
    // End of variables declaration//GEN-END:variables
}
